### ISSUE TITLE
Now the.whl file is gone. How can it be resolved?

### ISSUE THREAD

**Issue by luan1223** [delimitry/compressed_rtf#17]
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "……\compressed-rtf_4c49765f347041ae85467e8ef2b4fa70\setup.py", line 7, in <module>
          import compressed_rtf
      ModuleNotFoundError: No module named 'compressed_rtf'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by sht2017** [comment]
You may try the following steps if you are using it on win64:

1. Go check [sht2017/python-win64-embedded-patch](https://github.com/sht2017/python-win64-embedded-patch).
2. Download the [whole repository](https://github.com/sht2017/python-win64-embedded-patch/archive/refs/heads/main.zip), extract all files.
3. Execute start_build.bat, input you target python version(e.g. 3.11.9, executable files must valid on this version) then enter.
4. Sit and relax, if everything's fine you'll see the .whl in minutes.

**Comment by delimitry** [comment]
New release has whl file.
